### ISSUE TITLE
Is this something like DomDelegator?

### ISSUE THREAD

**Issue by ashnur** [benqus/doxxy#1]
> Note: Work In Progress - feel free to suggest ideas though tipping_hand_woman

I realized a long time ago that in general I do not actually want my DOM event handlers to be specified together with the layout. The reason being that many different UI implementations might use the same handler. 

The other, more important reason seems to be very connected with this module you are building here.
At the time when I was using mercury, the authors tried to separate it into 3 distinct parts, but because of the dom events, this was not working out really well. See the results here https://github.com/Raynos/mercury/blob/master/docs/modules/dom-delegator.md

**Comment by benqus** [comment]
> I realized a long time ago that in general I do not actually want my DOM event handlers to be specified together with the layout.

Fully agree. My thinking lately to allow the any DOM node or subtree to be created, manipulated and removed at any time, without any hassle, regardless of CSS animations and/or any other frameworks being present. Events should be bound to user-actions not to DOM implementations. This way we can change the markup as we don't care about where the listener is, we only care about what the user wants to do. Maintaining the DOM and it's state is expensive; simplest and (unsurprisingly) most performant way to manage a UI is letting browser do it's own thing, and I mean that literally. 😄 Especially when it comes to a frequently updating UI such as a trading application or a custom video player.

**Comment by benqus** [comment]
Sorry, I'm not familiar with that library
